
CREATE DATABASE IF NOT EXISTS NewCheck;
USE NewCheck;
CREATE TABLE IF NOT EXISTS TB_CLINICA ( ID_CLINICA INT NOT NULL AUTO_INCREMENT,
 NOME_CLINICA VARCHAR(50) NOT NULL, EMAIL_CLINICA VARCHAR(100) NOT NULL,
 TELEFONE_CLINICA VARCHAR(20),
 CNPJ_CLINICA VARCHAR(20),
 ESTADO_CLINICA VARCHAR(2),
 MUNICIPIO_CLINICA VARCHAR(40),
 ENDERECO_CLINICA VARCHAR(80),
 SENHA_CLINICA VARCHAR(255),
 PRIMARY KEY(ID_CLINICA) 
);
 
CREATE TABLE IF NOT EXISTS TB_CLIENTE ( CPF_CLIENTE VARCHAR(20) NOT NULL,
 NOME_CLIENTE VARCHAR(150) NOT NULL,
 IDADE_CLIENTE INT, SEXO_CLIENTE VARCHAR(1),
 EMAIL_CLIENTE VARCHAR(150),
 TELEFONE_CLIENTE VARCHAR(20),
 ESTADO_CLIENTE VARCHAR(2),
 MUNICIPIO_CLIENTE VARCHAR(40),
 ENDERECO_CLIENTE VARCHAR(80),
 SENHA_CLIENTE VARCHAR(255),
 PRIMARY KEY(CPF_CLIENTE) 
);

CREATE TABLE IF NOT EXISTS TB_MEDICO ( CRM_MEDICO VARCHAR(20) NOT NULL,
 TB_CLINICA_ID_CLINICA INT,
 EMAIL_MEDICO VARCHAR(150),
 TELEFONE_MEDICO VARCHAR(20),
 SENHA_MEDICO VARCHAR(255),
 PRIMARY KEY(CRM_MEDICO),
 FOREIGN KEY(TB_CLINICA_ID_CLINICA) REFERENCES TB_CLINICA(ID_CLINICA)
);

CREATE TABLE IF NOT EXISTS TB_CONSULTA ( ID_CONSULTA INT NOT NULL AUTO_INCREMENT,
 TB_MEDICO_CRM_MEDICO VARCHAR(20) NULL,
 TB_CLIENTE_CPF_CLIENTE VARCHAR(20) NULL, 
 TIPO_CONSULTA VARCHAR(50) NULL,
 DATAHORA_CONSULTA DATETIME NULL,
 PRECO_CONSULTA FLOAT,
 STATUS_CONSULTA VARCHAR(20) DEFAULT 'AGENDADA',
 PRIMARY KEY(ID_CONSULTA),
 FOREIGN KEY(TB_CLIENTE_CPF_CLIENTE) REFERENCES TB_CLIENTE(CPF_CLIENTE),
 FOREIGN KEY(TB_MEDICO_CRM_MEDICO) REFERENCES TB_MEDICO(CRM_MEDICO) 
);


insert into TB_MEDICO(CRM_MEDICO) values (115573);
insert into TB_CONSULTA(ID_CONSULTA) values(1234);
insert into TB_CLIENTE(CPF_CLIENTE,NOME_CLIENTE) values(15333546851,"João");

insert into TB_CONSULTA (ID_CONSULTA,TB_MEDICO_CRM_MEDICO,TB_CLIENTE_CPF_CLIENTE,TIPO_CONSULTA) values (12345,115.573,15333546851,"Oftalmologia");



select * from TB_MEDICO;

INSERT IGNORE INTO TB_MEDICO (CRM_MEDICO, TB_CLINICA_ID_CLINICA, EMAIL_MEDICO, TELEFONE_MEDICO, SENHA_MEDICO)
VALUES ('CRM12345', NULL, 'Dr. João', '11999990000', '');

INSERT IGNORE INTO TB_CLIENTE (CPF_CLIENTE, NOME_CLIENTE, IDADE_CLIENTE, SEXO_CLIENTE, EMAIL_CLIENTE, TELEFONE_CLIENTE, ESTADO_CLIENTE, MUNICIPIO_CLIENTE, ENDERECO_CLIENTE, SENHA_CLIENTE)
VALUES ('12345678900', 'Maria Silva', 30, 'F', 'maria@example.com', '11988887777', 'SP', 'São Paulo', 'Rua A, 123', '');

INSERT IGNORE INTO TB_CONSULTA (TB_MEDICO_CRM_MEDICO, TB_CLIENTE_CPF_CLIENTE, TIPO_CONSULTA, DATAHORA_CONSULTA, PRECO_CONSULTA, STATUS_CONSULTA)
VALUES ('CRM12345', '12345678900', 'Retorno', CONCAT(CURDATE(), ' 10:00:00'), 150.0, 'AGENDADA');

select * from TB_CONSULTA;
