-- init_db.sql
CREATE DATABASE IF NOT EXISTS sistema_agendamento;
USE sistema_agendamento;

CREATE TABLE IF NOT EXISTS TB_CLIENTE (
  CPF_CLIENTE VARCHAR(20) NOT NULL PRIMARY KEY,
  NOME_CLIENTE VARCHAR(150),
  IDADE_CLIENTE INT,
  SEXO_CLIENTE VARCHAR(10),
  EMAIL_CLIENTE VARCHAR(150),
  TELEFONE_CLIENTE VARCHAR(30),
  ESTADO_CLIENTE VARCHAR(50),
  MUNICIPIO_CLIENTE VARCHAR(100),
  ENDERECO_CLIENTE VARCHAR(255),
  SENHA_CLIENTE VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS TB_MEDICO (
  CRM_MEDICO VARCHAR(50) NOT NULL PRIMARY KEY,
  TB_CLINICA_ID_CLINICA INT DEFAULT NULL,
  EMAIL_MEDICO VARCHAR(150),
  TELEFONE_MEDICO VARCHAR(30),
  SENHA_MEDICO VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS TB_CONSULTA (
  ID_CONSULTA INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  TB_MEDICO_CRM_MEDICO VARCHAR(50),
  TB_CLIENTE_CPF_CLIENTE VARCHAR(20),
  TIPO_CONSULTA VARCHAR(50),
  DATAHORA_CONSULTA DATETIME,
  PRECO_CONSULTA FLOAT,
  STATUS_CONSULTA VARCHAR(20) DEFAULT 'AGENDADA',
  LATITUDE DECIMAL(10,8) NULL,
  LONGITUDE DECIMAL(11,8) NULL
);

INSERT IGNORE INTO TB_MEDICO (CRM_MEDICO, EMAIL_MEDICO, TELEFONE_MEDICO, SENHA_MEDICO)
VALUES ('CRM12345', 'dr@example.com', '11999990000', '');

INSERT IGNORE INTO TB_CLIENTE (CPF_CLIENTE, NOME_CLIENTE, EMAIL_CLIENTE, SENHA_CLIENTE)
VALUES ('12345678900', 'Maria Silva', 'maria@example.com', '');

INSERT IGNORE INTO TB_CONSULTA (TB_MEDICO_CRM_MEDICO, TB_CLIENTE_CPF_CLIENTE, TIPO_CONSULTA, DATAHORA_CONSULTA, PRECO_CONSULTA, STATUS_CONSULTA)
VALUES ('CRM12345', '12345678900', 'Retorno', CONCAT(CURDATE(), ' 10:00:00'), 150.0, 'AGENDADA');

ALTER TABLE TB_CONSULTA ADD COLUMN LATITUDE DECIMAL(10,8) NULL;
ALTER TABLE TB_CONSULTA ADD COLUMN LONGITUDE DECIMAL(11,8) NULL;