-- seed_medicos.sql
USE sistema_agendamento;

INSERT IGNORE INTO TB_MEDICO (CRM_MEDICO, EMAIL_MEDICO, TELEFONE_MEDICO, SENHA_MEDICO)
VALUES ('CRM12345', 'dr@example.com', '11999990000', '');

INSERT IGNORE INTO TB_CLIENTE (CPF_CLIENTE, NOME_CLIENTE, EMAIL_CLIENTE, SENHA_CLIENTE)
VALUES ('12345678900', 'Maria Silva', 'maria@example.com', '');

INSERT IGNORE INTO TB_CONSULTA (TB_MEDICO_CRM_MEDICO, TB_CLIENTE_CPF_CLIENTE, TIPO_CONSULTA, DATAHORA_CONSULTA, PRECO_CONSULTA, STATUS_CONSULTA)
VALUES ('CRM12345', '12345678900', 'Retorno', CONCAT(CURDATE(), ' 10:00:00'), 150.0, 'AGENDADA');
