create database sistema_agendamento;
use sistema_agendamento;

CREATE TABLE TB_CLINICA (
  ID_CLINICA INTEGER   NOT NULL ,
  NOME_CLINICA VARCHAR(50)   NOT NULL ,
  EMAIL_CLINICA VARCHAR(100)   NOT NULL ,
  TELEFONE_CLINICA INTEGER   NOT NULL ,
  CNPJ_CLINICA INTEGER   NOT NULL ,
  ESTADO_CLINICA VARCHAR(2)   NOT NULL ,
  MUNICIPIO_CLINICA VARCHAR(40)   NOT NULL ,
  ENDERECO_CLINICA VARCHAR(80)   NOT NULL ,
  SENHA_CLINICA VARCHAR(40)   NOT NULL   ,
PRIMARY KEY(ID_CLINICA));




CREATE TABLE TB_CLIENTE (
  CPF_CLIENTE INTEGER   NOT NULL ,
  NOME_CLIENTE VARCHAR(150)   NOT NULL ,
  IDADE_CLIENTE INTEGER   NOT NULL ,
  SEXO_CLIENTE VARCHAR(1)   NOT NULL ,
  EMAIL_CLIENTE VARCHAR(150)   NOT NULL ,
  TELEFONE_CLIENTE INTEGER   NOT NULL ,
  ESTADO_CLIENTE VARCHAR(2)   NOT NULL ,
  MUNICIPIO_CLIENTE VARCHAR(40)   NOT NULL ,
  ENDERECO_CLIENTE VARCHAR(80)   NOT NULL ,
  SENHA_CLIENTE VARCHAR(40)   NOT NULL   ,
PRIMARY KEY(CPF_CLIENTE));




CREATE TABLE TB_MEDICO (
  CRM_MEDICO VARCHAR(9)   NOT NULL ,
  TB_CLINICA_ID_CLINICA INTEGER   NOT NULL ,
  EMAIL_MEDICO VARCHAR(150)   NOT NULL ,
  TELEFONE_MEDICO INTEGER   NOT NULL ,
  SENHA_MEDICO VARCHAR(40)   NOT NULL   ,
PRIMARY KEY(CRM_MEDICO)  ,
  FOREIGN KEY(TB_CLINICA_ID_CLINICA)
    REFERENCES TB_CLINICA(ID_CLINICA));


CREATE INDEX TB_MEDICO_FKIndex1 ON TB_MEDICO (TB_CLINICA_ID_CLINICA);


CREATE INDEX IFK_trabalha ON TB_MEDICO (TB_CLINICA_ID_CLINICA);


CREATE TABLE TB_CONSULTA (
  ID_CONSULTA INTEGER   NOT NULL ,
  TB_MEDICO_CRM_MEDICO VARCHAR(9)   NOT NULL ,
  TB_CLIENTE_CPF_CLIENTE INTEGER   NOT NULL ,
  TIPO_CONSULTA VARCHAR(50)   NOT NULL ,
  DATAHORA_CONSULTA DATETIME   NOT NULL ,
  PRECO_CONSULTA FLOAT      ,
PRIMARY KEY(ID_CONSULTA)    ,
  FOREIGN KEY(TB_CLIENTE_CPF_CLIENTE)
    REFERENCES TB_CLIENTE(CPF_CLIENTE),
  FOREIGN KEY(TB_MEDICO_CRM_MEDICO)
    REFERENCES TB_MEDICO(CRM_MEDICO));


CREATE INDEX TB_CONSULTA_FKIndex1 ON TB_CONSULTA (TB_CLIENTE_CPF_CLIENTE);
CREATE INDEX TB_CONSULTA_FKIndex2 ON TB_CONSULTA (TB_MEDICO_CRM_MEDICO);


CREATE INDEX IFK_agenda ON TB_CONSULTA (TB_CLIENTE_CPF_CLIENTE);
CREATE INDEX IFK_atende ON TB_CONSULTA (TB_MEDICO_CRM_MEDICO);


CREATE TABLE TB_LAUDO (
  ID_LAUDO INTEGER   NOT NULL ,
  TB_CLIENTE_CPF_CLIENTE INTEGER   NOT NULL ,
  TB_MEDICO_CRM_MEDICO VARCHAR(9)   NOT NULL ,
  TB_CONSULTA_ID_CONSULTA INTEGER   NOT NULL ,
  CID_LAUDO VARCHAR(10)    ,
  DATAHORA_LAUDO DATETIME   NOT NULL ,
  PERIODOATESTADO_LAUDO TIMESTAMP      ,
PRIMARY KEY(ID_LAUDO)      ,
  FOREIGN KEY(TB_CONSULTA_ID_CONSULTA)
    REFERENCES TB_CONSULTA(ID_CONSULTA),
  FOREIGN KEY(TB_MEDICO_CRM_MEDICO)
    REFERENCES TB_MEDICO(CRM_MEDICO),
  FOREIGN KEY(TB_CLIENTE_CPF_CLIENTE)
    REFERENCES TB_CLIENTE(CPF_CLIENTE));


CREATE INDEX TB_LAUDO_FKIndex1 ON TB_LAUDO (TB_CONSULTA_ID_CONSULTA);
CREATE INDEX TB_LAUDO_FKIndex2 ON TB_LAUDO (TB_MEDICO_CRM_MEDICO);
CREATE INDEX TB_LAUDO_FKIndex3 ON TB_LAUDO (TB_CLIENTE_CPF_CLIENTE);


CREATE INDEX IFK_pertence ON TB_LAUDO (TB_CONSULTA_ID_CONSULTA);
CREATE INDEX IFK_prescreve ON TB_LAUDO (TB_MEDICO_CRM_MEDICO);
CREATE INDEX IFK_enviado ON TB_LAUDO (TB_CLIENTE_CPF_CLIENTE);



